{% set name = "pytest-robotframework" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_robotframework-{{ version }}.tar.gz
  sha256: 999326281bd2dd16bbc64f9dfbe6a544956968dc349e3479d571296867aba0c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pdm-backend
    - pip
  run:
    - ansi2html >=1.9.1
    - pluggy
    - typing_extensions
    - python >=3.8.0,<4.0.0
    - pytest <9,>=7
    - robotframework <8.0.0,>=6.1
    - deepmerge <2.0.0,>=1.1.0
    - basedtyping <0.2,>=0.1.0

test:
  imports:
    - pytest_robotframework
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/detachhead/pytest-robotframework
  summary: a pytest plugin that can run both python and robotframework tests while generating robot reports for them
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DetachHead
    - rxm7706
