{% set name = "pytest-robotframework" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_robotframework-{{ version }}.tar.gz
  sha256: 9d94b5c521abd399a442579585dd4f35a60a7708444b1adb118ee6b9c2a2d735

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pdm-backend
    - pip
  run:
    - pluggy
    - typing_extensions
    - python >=3.8.0,<4.0.0
    - pytest <8,>=7
    - robotframework <7.0.0,>=6.1.1
    - deepmerge <2.0.0,>=1.1.0
    - basedtyping <0.2,>=0.1.0

test:
  imports:
    - pytest_robotframework
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/detachhead/pytest-robotframework
  summary: a pytest plugin that can run both python and robotframework tests while generating robot reports for them
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DetachHead
    - rxm7706
