{% set name = "pytest-robotframework" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_robotframework-{{ version }}.tar.gz
  sha256: 34bc0adf2a1857f31f60515ba1500f30e58179f2302709c25c07113f5c1ebb38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - pdm-backend
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - pytest >=7.0.0,<8.0.0
    - robotframework >=6.1.1,<7.0.0
    - deepmerge >=1.1.0,<2.0.0
    - basedtyping >=0.0.3,<0.2

test:
  imports:
    - pytest_robotframework
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/detachhead/pytest-robotframework
  summary: a pytest plugin that can run both python and robotframework tests while generating robot reports for them
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DetachHead
    - rxm7706
