{% set name = "pytest-robotframework" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_robotframework-{{ version }}.tar.gz
  sha256: bc6d97788c2fed3a6e4f652a30c27db72452e8b81e2ea6dd985f3ac09d16d44c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - pluggy
    - typing_extensions
    - python >={{ python_min }},<4.0
    - pytest <9,>=7
    - robotframework <8.0.0,>=6.1
    - basedtyping <0.2,>=0.1.0
    - ansi2html >=1.9.1

test:
  imports:
    - pytest_robotframework
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/detachhead/pytest-robotframework
  summary: a pytest plugin that can run both python and robotframework tests while generating robot reports for them
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DetachHead
    - rxm7706
