{% set name = "pytest-robotframework" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_robotframework-{{ version }}.tar.gz
  sha256: 36ce98aa28fa214a7a2c09b90b99815fcabae5b2662167e7118026deaabd51a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pdm-backend
    - pip
  run:
    - python >=3.8,<4.0
    - pytest <9,>=7
    - robotframework <8.0.0,>=6.1
    - basedtyping <0.2,>=0.1.0
    - ansi2html >=1.9.1
# Not found in pyproject
    #- pluggy
    #- typing_extensions
    #- deepmerge <2.0.0,>=1.1.0

test:
  imports:
    - pytest_robotframework
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/detachhead/pytest-robotframework
  summary: a pytest plugin that can run both python and robotframework tests while generating robot reports for them
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DetachHead
    - rxm7706
